version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: documind-postgres
    environment:
      POSTGRES_USER: documind
      POSTGRES_PASSWORD: documind
      POSTGRES_DB: documind
    ports:
      - "5432:5432"
    volumes:
      - documind_pgdata:/var/lib/postgresql/data

volumes:
  documind_pgdata:
